version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"

- package-ecosystem: "maven"
  directory: "/testapiconnector"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "fix"
    prefix-development: "chore"
    include: "scope"
