version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(ci dep)"
      include: "scope"

- package-ecosystem: "maven"
  directory: "/testapiconnector"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "fix(maven dep)"
    prefix-development: "chore(maven dev dep)"
    include: "scope"
