language: java
dist: xenial
notifications:
  email:
    recipients:
    - kschwarz@hexonet.net
    on_success: never
    on_failure: always
jdk:
  - oraclejdk11
  - openjdk11
  - openjdk-ea
matrix:
  allow_failures:
    - jdk: openjdk-ea
install: skip
script:
  - cd testapiconnector && mvn compile exec:java
