name: Release
on: [push, pull_request]

jobs:
  test:
    name: Test @ Java ${{ matrix.java-version }} - x86 - ubuntu-latest
    # Support [skip ci] out of box with github actions Workaround
    # Only works for push https://github.com/actions/runner/issues/774
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && contains(toJson(github.event.commits), '[skip ci]') == false)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [15]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - run: |
          cd testapiconnector 
          mvn compile exec:java
